
-- Tablas sin dependencias
CREATE TABLE public."Commissions" (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE public."Companies" (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    rif text NOT NULL,
    email text,
    phone text,
    address text,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE public."EventCategories" (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

-- RBAC Tables
CREATE TABLE public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE public.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action text NOT NULL,
    subject text NOT NULL,
    UNIQUE(action, subject)
);

CREATE TABLE public.rolepermissions (
    role_id bigint REFERENCES public.roles(id) ON DELETE CASCADE,
    permission_id bigint REFERENCES public.permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE public.userprofiles (
    id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name text,
    role_id bigint REFERENCES public.roles(id) ON DELETE SET NULL,
    is_approved boolean DEFAULT false
);

CREATE TABLE public.departments (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL UNIQUE,
    description text,
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz,
    created_by uuid REFERENCES auth.users(id),
    updated_by uuid REFERENCES auth.users(id)
);

-- Tablas con dependencias
CREATE TABLE public."Events" (
    id text NOT NULL PRIMARY KEY,
    subject text NOT NULL,
    date date NOT NULL,
    start_time text NOT NULL,
    end_time text,
    location text,
    external_participants_count integer DEFAULT 0,
    description text,
    cost numeric,
    investment numeric,
    revenue numeric,
    is_cancelled boolean NOT NULL DEFAULT false,
    flyer_url text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz,
    created_by uuid REFERENCES auth.users(id),
    updated_by uuid REFERENCES auth.users(id)
);

CREATE TABLE public."Meetings" (
    id text NOT NULL PRIMARY KEY,
    subject text,
    commission_id text NOT NULL REFERENCES public."Commissions"(id),
    date date NOT NULL,
    start_time text,
    end_time text,
    location text,
    external_participants_count integer DEFAULT 0,
    description text,
    is_cancelled boolean NOT NULL DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz,
    created_by uuid REFERENCES auth.users(id),
    updated_by uuid REFERENCES auth.users(id)
);

CREATE TABLE public."Participants" (
    id text NOT NULL PRIMARY KEY,
    name text NOT NULL,
    id_establecimiento text, -- Reference handled in app logic or via foreign key if table exists
    role text,
    email text,
    phone text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz,
    created_by uuid REFERENCES auth.users(id),
    updated_by uuid REFERENCES auth.users(id)
);

CREATE TABLE public.tasks (
    id text NOT NULL PRIMARY KEY,
    title text NOT NULL,
    description text,
    status text CHECK (status IN ('pending', 'in_progress', 'completed')) DEFAULT 'pending',
    priority text CHECK (priority IN ('low', 'medium', 'high')) DEFAULT 'medium',
    department_id text REFERENCES public.departments(id) ON DELETE SET NULL,
    created_by uuid REFERENCES auth.users(id),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz
);

CREATE TABLE public.task_schedules (
    id text NOT NULL PRIMARY KEY,
    task_id text REFERENCES public.tasks(id) ON DELETE CASCADE,
    date date NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL
);

-- Tablas de unión (Join Tables)
CREATE TABLE public.event_attendees (
    event_id text NOT NULL REFERENCES public."Events"(id) ON DELETE CASCADE,
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    attendance_type text NOT NULL,
    PRIMARY KEY (event_id, participant_id)
);

CREATE TABLE public.event_invitees (
    event_id text NOT NULL REFERENCES public."Events"(id) ON DELETE CASCADE,
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, participant_id)
);

CREATE TABLE public.event_organizing_categories (
    event_id text NOT NULL REFERENCES public."Events"(id) ON DELETE CASCADE,
    category_id text NOT NULL REFERENCES public."EventCategories"(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, category_id)
);

CREATE TABLE public.event_organizing_commissions (
    event_id text NOT NULL REFERENCES public."Events"(id) ON DELETE CASCADE,
    commission_id text NOT NULL REFERENCES public."Commissions"(id) ON DELETE CASCADE,
    PRIMARY KEY (event_id, commission_id)
);

CREATE TABLE public.meeting_attendees (
    meeting_id text NOT NULL REFERENCES public."Meetings"(id) ON DELETE CASCADE,
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    attendance_type text NOT NULL,
    PRIMARY KEY (meeting_id, participant_id)
);

CREATE TABLE public.meeting_invitees (
    meeting_id text NOT NULL REFERENCES public."Meetings"(id) ON DELETE CASCADE,
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    PRIMARY KEY (meeting_id, participant_id)
);

CREATE TABLE public.participant_commissions (
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    commission_id text NOT NULL REFERENCES public."Commissions"(id) ON DELETE CASCADE,
    PRIMARY KEY (participant_id, commission_id)
);

CREATE TABLE public.participant_departments (
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    department_id text NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
    PRIMARY KEY (participant_id, department_id)
);

CREATE TABLE public.user_departments (
    user_id uuid NOT NULL REFERENCES public.userprofiles(id) ON DELETE CASCADE,
    department_id text NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, department_id)
);

CREATE TABLE public.task_assignments (
    task_id text NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    participant_id text NOT NULL REFERENCES public."Participants"(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, participant_id)
);

CREATE TABLE public.task_user_assignments (
    task_id text NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES public.userprofiles(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, user_id)
);

-- Permisos necesarios para la API
ALTER TABLE public."Commissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventCategories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Meetings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Participants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rolepermissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.userprofiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Policies (Simplified for development - allow authenticated users to read)
CREATE POLICY "Enable read access for authenticated users" ON public."Commissions" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public."Companies" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public."EventCategories" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public."Events" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public."Meetings" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public."Participants" FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.roles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.permissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.rolepermissions FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.userprofiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.departments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read access for authenticated users" ON public.tasks FOR SELECT TO authenticated USING (true);

-- Allow full access for now (can be restricted later based on admin role)
CREATE POLICY "Enable all access for authenticated users" ON public."Commissions" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."Companies" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."EventCategories" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."Events" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."Meetings" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public."Participants" FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.roles FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.permissions FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.rolepermissions FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.userprofiles FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.departments FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all access for authenticated users" ON public.tasks FOR ALL TO authenticated USING (true);

-- Grant Access
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
